// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn5j0BYBnkS7mELlgQIp_9vxaJ5OotkhY',
    appId: '1:383487606697:web:b5545bed0612a354800eb8',
    messagingSenderId: '383487606697',
    projectId: 'fluttertraningfirebase',
    authDomain: 'fluttertraningfirebase.firebaseapp.com',
    storageBucket: 'fluttertraningfirebase.appspot.com',
    measurementId: 'G-3JSSF11WLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTKIecSpvKFKT_m3JjOO2DKRlODcJzg3c',
    appId: '1:383487606697:android:745ff02c3a877011800eb8',
    messagingSenderId: '383487606697',
    projectId: 'fluttertraningfirebase',
    storageBucket: 'fluttertraningfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmrp1Ua7kYwN-No5HsHsYhJEFgFWWLErw',
    appId: '1:383487606697:ios:9107c6476ea816bd800eb8',
    messagingSenderId: '383487606697',
    projectId: 'fluttertraningfirebase',
    storageBucket: 'fluttertraningfirebase.appspot.com',
    iosBundleId: 'com.example.firebasetraning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmrp1Ua7kYwN-No5HsHsYhJEFgFWWLErw',
    appId: '1:383487606697:ios:0336ed9f26f9d62a800eb8',
    messagingSenderId: '383487606697',
    projectId: 'fluttertraningfirebase',
    storageBucket: 'fluttertraningfirebase.appspot.com',
    iosBundleId: 'com.example.firebasetraning.RunnerTests',
  );
}
